Added matrix multiplication
MikhailNakhatovich/gpu-labs pull request #1
Opened 2021-03-12 20:28 UTC by MikhailNakhatovich

2021-03-25 18:46 UTC, Kauter1989 requested changes

2021-03-25 18:46 UTC, Kauter1989 commented on lab-1/lab-1/main.cu
> +            for (size_t k = 0; k < size; c[cellIndex] += a[i * size + k] * b[k * size + j], ++k);
Исправьте цикл в одну строчку, такое не пишут нигде

2021-03-25 18:46 UTC, Kauter1989 commented on lab-1/lab-1/main.cu
> +    for (size_t k = 0; k < size; c[cellIndex] += a[i * size + k] * b[k * size + j], ++k);
см выше: вы таким образом путаете условие и переход итерации с логикой самой итерации, это ошибка и она снижает читаемость

2021-03-25 18:46 UTC, Kauter1989 commented on lab-1/lab-1/main.cu
> +    cudaMalloc(reinterpret_cast<void**>(&adev), numBytes);
обоснуйте reinterpret_cast

2021-03-25 18:46 UTC, Kauter1989 commented on lab-1/lab-1/main.cu
> +    double* a = generateMatrix(size), *b = generateMatrix(size);
переменные должны инициализироваться в разных строчках

2021-03-25 18:46 UTC, Kauter1989 commented on lab-1/lab-1/main.cu
> +    double* a = generateMatrix(size), *b = generateMatrix(size);
generateMatrix() обладает правом выделить память, однако в дальнейшем нет никакой функции, контролирующей корректность удаления

2021-03-26 20:21 UTC, MikhailNakhatovich commented on lab-1/lab-1/main.cu
> +    cudaMalloc(reinterpret_cast<void**>(&adev), numBytes);
`reinterpret_cast` делает то, что мне нужно - он может привести один тип в любой другой. В данном случае я знаю, что приведение типа будет удачным, поэтому и использую данный оператор приведения типа вместо, например, `dynamic_cast`. Можно было бы использовать, например, приведение в стиле C, но мы ведь пишем на C++, поэтому я считаю, что нужно использовать `*_cast` операторы.

2021-03-26 22:25 UTC, Kauter1989 commented on lab-1/lab-1/main.cu
> +    cudaMalloc(reinterpret_cast<void**>(&adev), numBytes);
Это неверный аргумент. Существует множество инструментов, позволяющих сделать конверсию типов данных, однако вы выбрали из возможных наиболее небезопасный. Ключевое правило - при всех возможных нарушениях безопасности надо выбирать такой инструмент, который осуществляет минимальное их количество при исполнении той же задачи. В данном случае это static_cast. dynamic_cast основан вообще на RTTI и применим к конверсиям в рамках классов и иерархий, здесь он неуместен и вызовет ошибку - это вы должны знать, между прочим. Код не должен быть спроектирован исходя из ваших личных предпочтений по безопасности той или иной операции - если так будут делать все, ни один проект невозможно будет сделать без критических ошибок

2021-03-26 23:23 UTC, MikhailNakhatovich commented on lab-1/lab-1/main.cu
> +    cudaMalloc(reinterpret_cast<void**>(&adev), numBytes);
Точно, `dynamic_cast` тут не уместен. Но и `static_cast` тут не поможет, так как он не может выполнить приведение к `void**`. А приведение типов в стиле C в итоге будет эквивалентно применению `reinterpret_cast`.

2021-04-11 12:05 UTC, merged